### ISSUE TITLE
Ask a question

### ISSUE THREAD

**Issue by Jayxiang** [AbedElazizShe/LightCompressor_iOS#2]
Why choose `very_high` bitrate to use `Int(bitrate * 0.5)` instead of `Int(bitrate * 0.8)`. When I change it to `Int(bitrate * 0.8)` or other higher coefficients in the project, the compressed video will not play normally. So I want to know why you use `Int(bitrate * 0.5)`.

**Comment by AbedElazizShe** [comment]
@Jayxiang thank you for opening this issue. To be honest, I haven't tried to get that high. The videos have reasonable resolution when I tested 0.5 including the Android library so I decided to use that value. I will spend sometime to try different values and will let you know of the findings.

**Comment by Jayxiang** [comment]
@AbedElazizShe  Did you find anything?
